ak_immobilier_homepage:

    path:     /front
    defaults: { _controller: AKImmobilierBundle:Front:viewBien }

  


# etat:
#     path:     /front/{id}
#     defaults: { _controller: AKImmobilierBundle:Front:etatBien }
#     requirements: 
#         id: \d+
#     path:     /
#     defaults: { _controller: AKImmobilierBundle:Default:index }





    
