ak_immobilier_homepage:

    path:     /front/
    defaults: { _controller: AKImmobilierBundle:Front:viewBien }

search:
    path:     /front/search
    defaults: { _controller: AKImmobilierBundle:Front:searchBien }

reserver:
    path:     /front/reserver/{id}
    defaults: { _controller: AKImmobilierBundle:Front:reserver }
    requirements:
        id: \d+

contrat:
    path:     /admin/contrat
    defaults: { _controller: AKImmobilierBundle:Admin:contrat }

validreserv:
    path:     /admin/validreserv
    defaults: { _controller: AKImmobilierBundle:Admin:validreserv }


# register:
#     path:     /register
#     defaults: { _controller: FOSUserBundle:Registration:registration.xml}





# etat:
#     path:     /front/{id}
#     defaults: { _controller: AKImmobilierBundle:Front:etatBien }
#     requirements: 
#         id: \d+
#     path:     /
#     defaults: { _controller: AKImmobilierBundle:Default:index }





    
