ak_immobilier_homepage:

    path:     /front
    defaults: { _controller: AKImmobilierBundle:Front:viewBien }

search:
    path:     /front/search
    defaults: { _controller: AKImmobilierBundle:Front:searchBien }

reservateBien:
    path:     /front/reserver
    defaults: { _controller: AKImmobilierBundle:Front:reservateBien }         

  


# etat:
#     path:     /front/{id}
#     defaults: { _controller: AKImmobilierBundle:Front:etatBien }
#     requirements: 
#         id: \d+
#     path:     /
#     defaults: { _controller: AKImmobilierBundle:Default:index }





    
