<?php

namespace AK\ImmobilierBundle\Repository;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
{
   
    public function getLocalite()
    {
        $em=$this->getEntityManager()->createQueryBuilder();
        $dql=$em->select('b','l')
        ->from('AKImmoblierBundle:Bien','b')
        ->leftJoin('b.localite','l')
        ->where('b.localite = l.nomlocalite')
        //->setParameter()
        ->getQuery();
        return $dql->getResult();
    }
    public function getType()
    {
        $em=$this->getEntityManager()->createQueryBuilder();
        $dql=$em->select('b','t')
        ->from('AKImmoblierBundle:Bien','b')
        ->leftJoin('b.typebien','t')
        ->where('b.typebien = t.libelle')
        //->setParameter()
        ->getQuery();
        return $dql->getResult();
    }

    public function findImage()
    {
        $em=$this->getEntityManager()->createQueryBuilder();
        $dql=$em->select('b','i')
        ->from('AKImmoblierBundle:Bien','b')
        ->leftJoin('i.bien','b')
        ->where('i.bien = b.id')
        //->setParameters()
        ->getQuery();
        $image=$dql->getImages();
        return $image->getResult();
    }
    
    public function findBiens($localite , $typebien , $prixlocation )
    {
        $dql = "SELECT b, i FROM AK\ImmobilierBundle\Entity\Bien b 
        left Join b.images i Join b.typebien t Join b.localite l WHERE b.etat = 0";
        if ($localite != 0) {
            $dql .= ' AND l.id = :localite_id';
        }
        if (isset($typebien) && empty($localite) && empty($prixlocation) ) {
            $dql .= ' AND t.id = :typebien_id';
            $dql->setParameter('typebien_id', $typebien);
        }
        if ($prixlocation != 0) {
            $dql .= ' AND b.prixlocation BETWEEN :prixMin AND :prixMax';
        }

        $query = $this->getEntityManager()->createQuery($dql);

        if ($localite != 0) {
            $query->setParameter('localite_id', $localite);
        }
        if ($typebien != 0) {
            $query->setParameter('typebien_id', $typebien);
        }
        if ($prixlocation != 0) {
            $query->setParameter('prixMin', $prixlocation - 10000)
            ->setParameter('prixMax', $prixlocation + 20000);
        }

        return $query->getResult();
    }
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}
