<?php

namespace AK\ImmobilierBundle\Repository;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
{
   
    public function getLocalite()
    {
        $em=$this->getEntityManager()->createQueryBuilder();
        $dql=$em->select('b','l')
        ->from('AKImmoblierBundle:Bien','b')
        ->leftJoin('b.localite','l')
        ->where('b.localite = l.nomlocalite')
        //->setParameter()
        ->getQuery();
        return $dql->getResult();
    }
    public function getType()
    {
        $em=$this->getEntityManager()->createQueryBuilder();
        $dql=$em->select('b','t')
        ->from('AKImmoblierBundle:Bien','b')
        ->leftJoin('b.typebien','t')
        ->where('b.typebien = t.libelle')
        //->setParameter()
        ->getQuery();
        return $dql->getResult();
    }

    public function findImage()
    {
        $em=$this->getEntityManager()->createQueryBuilder();
        $dql=$em->select('b','i')
        ->from('AKImmoblierBundle:Bien','b')
        ->leftJoin('i.bien','b')
        ->where('i.bien = b.id')
        //->setParameters()
        ->getQuery();
        $image=$dql->getImages();
        return $image->getResult();
    }
    
     public function findBien($localite=0 , $typebien=0 ,$prixmin=0,$prixmax=0)
     {
        $dql = "SELECT b, i FROM AK\ImmobilierBundle\Entity\Bien b 
        left Join b.images i Join b.typebien t Join b.localite l WHERE b.etat = 1";
        if ($localite != 0) {
            $dql .= ' OR l.id = :idLoc';
        }
        if ($typebien != 0) {
            $dql .= ' OR t.id = :idType';
        }
        if ($prixmax != 0 && $prixmin != 0) {
            $dql .= ' OR b.prixlocation BETWEEN :prixMin AND :prixMax';
        }

        $query = $this->getEntityManager()->createQuery($dql);

        if ($localite != 0) {
            $query->setParameter('idLoc', $localite);
        }
        if ($typebien != 0) {
            $query->setParameter('idType', $typebien);
        }
        if ($prixmax != 0 && $prixmin != 0 )
         {
            $query->setParameter('prixMin',$prixmin) 
                ->setParameter('prixMax', $prixmax);
            
        }
     

        return $query->getResult();
      
        // $query = $this->createQueryBuilder('b')
        // ->join('b.localite', 'l')
        // ->join('b.typebien', 't')
        // ->addSelect('l')
        // ->addSelect('t')
        // ->where('l.id = :localite OR t.id = :type AND(l.id=:localite AND t.id=:type)')
        // // ->andwhere('l.id=:localite AND t.id=:type')
        // ->setParameters(array('localite' => $localite, 'type' => $typebien));

        // return $query->getQuery()->getResult();
       
    //     $query = $this->getEntityManager()->createQuery(
    //         'SELECT b FROM AKImmobilierBundle:Bien b 
    //             WHERE 
    //             b.localite in (SELECT l.id FROM AKImmobilierBundle:Localite l WHERE l.nomlocalite like :localite ) 
    //             AND 
    //             b.typebien in (SELECT t.id FROM AKImmobilierBundle:Typebien t WHERE t.libelle like :typebien )'
    // )->setParameter(
    //     'localite', $localite
    // )->setParameter(
    //     'typebien', $typebien
    // );

    // return $query->getResult();
    }
    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
}
