<?php

namespace AK\ImmobilierBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getImage()
    {
        $em=$this->getEntityManager()->createQueryBuilder();
        $dql=$em->select('i','b')
        ->from('AKImmoblierBundle:Image','i')
        ->leftJoin('i.bien','b')
        ->where('i.bien = b.id')
        //->setParameter()
        ->getQuery();
        return $dql->getResult();
    }
}
