<?php

namespace AK\ImmobilierBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{

    // public function findReservationByValues($bien, $client){

    //     $query = $this->getEntityManager()->createQuery(
    //             'SELECT b FROM AKImmobilierBundle:Reservation r
    //                 WHERE
    //                 r.bien in (SELECT b.id FROM AKImmobilierBundle:Bien b WHERE b.nombien like :bien )
    //                 AND
    //                 r.client in (SELECT c.id FROM AKImmobilierBundle:Client c WHERE c.nom like :client )'
    //     )->setParameter(
    //         'bien', $bien
    //     )->setParameter(
    //         'client', $client
    //     );

    //     return $query->execute();
    // }
}
