<?php

namespace AK\ImmobilierBundle\Repository;

/**
 * TypebienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypebienRepository extends \Doctrine\ORM\EntityRepository
{
}
